server:
  port: 8080

domain: localhost:8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: subdomain_ingress_route
              uri: lb://port-buddy-server
              predicates:
                - Host={subdomain}.${domain}
              filters:
                - name: RewritePath
                  args:
                    regexp: /(?<path>.*)
                    replacement: /_/${subdomain}/$\\{path}

            - id: api_route
              order: 2
              uri: lb://port-buddy-server
              predicates:
                - Path=/api/**




